### ISSUE TITLE
Even if I ship an order without MyParcel the url of the shipment refers to https://myparcel.me

### ISSUE THREAD

**Issue by gerben86** [myparcelnl/magento#699]
### Plugin version

4.5.0 and 4.9.0

### Magento version

2.4.4

### PHP version

7.4.30

### What went wrong?

When an order should be shipped via MyParcel but I decide to use another shipping company I past the track-and-trace-url of that company in the field 'number' in the Magento Backend. 
I also deselect the 'Create MyParcel consignment'. Check the printscreen below:
![image](https://user-images.githubusercontent.com/17478858/176233772-201ed625-ff98-4d1a-b9be-e15013c4f12a.png)

However, in the shipmentmail send to the customer the url looks like this: https://myparcel.me/track-trace/https://www.dhlparcel.nl/nl/particulier/ontvangen/volg-uw-zending?tt=J123123123&pc=1234AB/1234AB/NL
So it's redirected to https://myparcel.me, which results in a 404.

Why are you modifying the field 'Number' if the shipment isn't actually done via MyParcel?
This has customer impact, because I get complaints that the url isn't usable...

The url is generated in this file 'sdk/src/Helper/TrackTraceUrl.php'. There should be a check that it's actually shipped via MyParcel and only then the url should be created in this way, otherwise leave the 'shipment number' untouched.

Is there anyone who can provide me with a temporarily workaround, so that both the orders via MyParcel (90% of the orders) and the orders via another shippingcompany are processed fine?

Thanks!

Edit:
I added this as a temporarily workaround (just check if the value contains DHL, then don't modify it):
![image](https://user-images.githubusercontent.com/17478858/176242299-f69c9068-2371-482a-b11e-4d689adc2aa8.png)

### Reproduction steps

See above

**Comment by RichardPerdaan** [comment]
Fixed in [v4.6.0](https://github.com/myparcelnl/magento/releases/tag/v4.6.0)

**Comment by gerben86** [comment]
I'm using now version 4.9.0 and this issue is back again...
So please reopen this issue

**Comment by gerben86** [comment]
More then 1 year after creating the initial bug and half a year after reopening the ticket this is still existing...

While the fix is quite easy, as mentioned in the first comment.

**Comment by gerben86** [comment]
Issue still in v4.12.0
